### ISSUE TITLE
Move instructions into their own panel

### ISSUE THREAD

**Issue by danielcompton** [daiyi/demos#3]
It would be good for the instructions to be a toggleable panel next to the `:docs` link which explained how to use it, if they were linked there from somewhere that wasn't the homepage.

<img width="530" alt="screenshot of google chrome 19-07-17 2-22-13 pm" src="https://user-images.githubusercontent.com/811954/28347843-ab8e5bf0-6c8d-11e7-9a68-8af099ba8a51.png">

**Comment by daiyi** [comment]
instructions are moved to their own gist and linked in the top left: http://www.daiyi.co/demos/re-playground/?gist-id=daiyi/62db9d22136503a42cbbe5dc5ec0337d
